version: '3.1'
services:
  
  account-and-token-mysqldb:
    image: mysql:5.7
    volumes:
      - ./mysqldb:/docker-entrypoint-initdb.d
      - account-and-token-mysqldb-volume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: accountDB
    ports:
      - 3600:3306
      
volumes:
  account-and-token-mysqldb-volume:
