server:
  servlet:
    context-path: /accounts
  port: 6000

security:
  oauth2:
    client:
      checkTokenEndpointUrl: http://auth-service:6666/auth/oauth/check_token
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:6666/auth/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  devtools:
    remote:
      secret: h1
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://account-and-token-mysqldb:3306/accountDB?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: ${MYSQLDB_ROOT_PASSWORD}
    jpa:
      database-platform: org.hibernate.dialect.MySQLInnoDBDialect