server:
  servlet:
    context-path: /
  port: 6000

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://account-mysqldb:3306/accountDB?serverTimezone=UTC
    username: root
    password: ${MYSQLDB_ROOT_PASSWORD}
    jpa:
      database-platform: org.hibernate.dialect.MySQLInnoDBDialect