logging:
  level:
    org.springframework.security: INFO

eureka:
  #instance:
    #prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka-server:9999/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:6666/auth/accounts/current