server:
  servlet:
    context-path: /auth
  port: 6666

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://account-and-token-mysqldb:3306/accountDB?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: ${MYSQLDB_ROOT_PASSWORD}
    jpa:
      database-platform: org.hibernate.dialect.MySQLInnoDBDialect
  token-datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://account-and-token-mysqldb:3306/tokenDB?serverTimezone=UTC
    username: root
    password: ${MYSQLDB_ROOT_PASSWORD}
    jpa:
      database-platform: org.hibernate.dialect.MySQLInnoDBDialect

