spring:
  jpa:
    open-in-view: false
  cloud:
    config:
      server:
        #git:
          #uri: https://github.com/Debski-A/money-saver-configs
        native:
          search-locations: classpath:/shared
  profiles:
    active: native
server:
  port: 8888

